# Generated by Django 6.0.3 on 2026-03-22 17:26

import apps.submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0004_add_indexes_and_elixir_year_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesubmission",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Optional service logo (PNG, JPEG, or SVG). Max 10 MB. Old logo files are retained on disk when replaced.",
                null=True,
                upload_to=apps.submissions.models._logo_upload_to,
            ),
        ),
    ]
