# Generated by Django 6.0.3 on 2026-04-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0009_add_submission_change_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicesubmission",
            name="kpi_start_year",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Year KPI monitoring started, or estimated start year if planned. Use YYYY format or a short description. Not required when KPI monitoring is set to 'Planned'.",
                max_length=100,
            ),
        ),
    ]
