# Generated by Django 6.0.3 on 2026-04-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0013_license_remove_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionDeletionAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_id",
                    models.UUIDField(
                        db_index=True,
                        editable=False,
                        help_text="PK of the deleted ServiceSubmission.",
                    ),
                ),
                ("service_name", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        help_text="Status of the submission at the time of deletion.",
                        max_length=20,
                    ),
                ),
                ("submitter_first_name", models.CharField(blank=True, max_length=100)),
                ("submitter_last_name", models.CharField(blank=True, max_length=100)),
                ("submitter_affiliation", models.CharField(blank=True, max_length=300)),
                ("public_contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "deleted_by",
                    models.CharField(
                        help_text='Who performed the deletion. Format: "admin:<username>" or "system".',
                        max_length=200,
                    ),
                ),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changelog_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of SubmissionChangeLog entries that were cascade-deleted.",
                    ),
                ),
                (
                    "changelog_snapshot",
                    models.JSONField(
                        default=list,
                        help_text="Full snapshot of all SubmissionChangeLog entries at time of deletion.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deletion Audit",
                "verbose_name_plural": "Deletion Audits",
                "ordering": ["-deleted_at"],
            },
        ),
    ]
