# Generated by Django 6.0.3 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0014_add_submission_deletion_audit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicesubmission",
            name="last_change_summary",
            field=models.JSONField(
                blank=True,
                null=True,
                help_text=(
                    "Structured record of the most recent field-level change. "
                    "Written by EditView (submitter), ServiceSubmissionAdmin (admin), "
                    "or API PATCH (api key). Schema: "
                    '{"changed_by": "submitter|admin:<username>|api:<key_label>", '
                    '"changed_at": "<ISO-8601>", '
                    '"changes": [{"field":…, "label":…, "old":…, "new":…}]}'
                ),
            ),
        ),
    ]
