# Generated by Django 6.0.5 on 2026-05-12 14:53

import apps.submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0017_add_catalogue_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicesubmission",
            name="public_contact_email",
            field=models.CharField(
                help_text="Contact email address or support URL displayed publicly on the de.NBI services page. This value is publicly visible.",
                max_length=2000,
                validators=[apps.submissions.models._validate_public_contact],
            ),
        ),
        migrations.AlterField(
            model_name="submissiondeletionaudit",
            name="public_contact_email",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
