# Generated by Django 6.0.8 on 2026-10-01 21:07

import apps.submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0018_expand_public_contact_to_charfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicesubmission",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Optional service logo (PNG, JPEG, or SVG). Size limits are set in config/site.toml [uploads]. Old logo files are retained on disk when replaced.",
                null=True,
                upload_to=apps.submissions.models._logo_upload_to,
            ),
        ),
    ]
