# Generated by Django 6.0.3 on 2026-04-03 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAPIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hex digest of the plaintext key.  Never stored in cleartext.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable name for this key (e.g. 'Public website', 'CI pipeline').",
                        max_length=100,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("read", "Read-only — GET / HEAD / OPTIONS only"),
                            ("full", "Full access — all HTTP methods"),
                        ],
                        default="full",
                        help_text="read = safe HTTP methods only (GET/HEAD/OPTIONS); full = all HTTP methods including POST/PATCH/DELETE.",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Revoke by setting to False.  The record is retained for audit purposes.",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the most recent successfully authenticated request.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff user who created this key.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin API Key",
                "verbose_name_plural": "Admin API Keys",
                "ordering": ["-created_at"],
            },
        ),
    ]
