# Generated by Django 6.0.4 on 2026-04-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpdxLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_id",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical SPDX short identifier, e.g. 'Apache-2.0'.",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Full human-readable license name, e.g. 'Apache License 2.0'.",
                        max_length=200,
                    ),
                ),
                (
                    "reference_url",
                    models.URLField(
                        blank=True,
                        help_text="Canonical SPDX reference page for this license.",
                        max_length=500,
                    ),
                ),
                (
                    "see_also",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Additional authoritative URLs for the license text.",
                    ),
                ),
                (
                    "is_osi_approved",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when the license is approved by the Open Source Initiative.",
                    ),
                ),
                (
                    "is_fsf_libre",
                    models.BooleanField(
                        default=False,
                        help_text="True when the Free Software Foundation considers the license libre.",
                    ),
                ),
                (
                    "is_deprecated",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Deprecated licenses are hidden from new selections but retained for historical submission references.",
                    ),
                ),
                (
                    "spdx_version",
                    models.CharField(
                        blank=True,
                        help_text="SPDX License List release version this row was last updated from, e.g. '3.26'.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "SPDX License",
                "verbose_name_plural": "SPDX Licenses",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_deprecated", "name"],
                        name="licenses_sp_is_depr_6fc8e8_idx",
                    )
                ],
            },
        ),
    ]
